### ISSUE TITLE
加个字体修改功能

### ISSUE THREAD

**Issue by MoeX1n** [BetterQQNT/BetterQQNT#43]
跟betterncm的插件一样可以修改界面的字体

**Comment by lgc2333** [comment]
自定义CSS：

```css
body {
  font-family: 'LXGW Wenkai', 'JetBrainsMono Nerd Font', 'Microsoft YaHei UI', sans-serif !important;
}
```
